name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: mkdir -p output

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk texlive-bibtex-extra biber texlive-lang-german texlive-pstricks
    - name: Build document
      run: make

    - uses: actions/upload-artifact@v4
      with:
          name: cv_english.pdf
          path: output/en/en.pdf

    - uses: actions/upload-artifact@v4
      with:
          name: cv_deutsch.pdf
          path: output/de/de.pdf
